name: paper
adopt-info: paper
base: core22
grade: stable
confinement: strict
compression: lzo
contact: soumyadeepghosh2004@zohomail.in

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

parts:
  paper:
    plugin: meson
    source: https://gitlab.com/posidon_software/paper.git
    source-tag: '22.11'
    source-depth: 1
    meson-parameters:
      - --prefix=/usr
    parse-info: [usr/share/metainfo/io.posidon.Paper.appdata.xml]
    build-snaps:
      - blueprint-compiler
    override-pull: |
      craftctl default
      patch -p1 < $CRAFT_PROJECT_DIR/paper.patch
    override-build: |
      craftctl default
      mkdir -p $CRAFT_PART_INSTALL/meta/gui
      cp -r $CRAFT_PART_INSTALL/usr/share/icons $CRAFT_PART_INSTALL/meta/gui/
      for i in `find $CRAFT_PART_INSTALL/meta/gui/icons -name "*.svg" -o -name "*.png"`; do
        mv $i "`dirname $i`/snap.$CRAFT_PROJECT_NAME.`basename $i`"
      done

slots:
  paper:
    interface: dbus
    bus: session
    name: io.posidon.Paper

apps:
  paper:
    command: usr/bin/io.posidon.Paper
    common-id: io.posidon.Paper
    extensions: [gnome]
    desktop: usr/share/applications/io.posidon.Paper.desktop
    plugs:
      - home
      - removable-media
