name: paper
adopt-info: paper
base: core22
grade: stable
confinement: strict
compression: lzo
contact: soumyadeepghosh2004@zohomail.in

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

parts:
  paper:
    plugin: meson
    source: https://gitlab.com/posidon_software/paper.git
    source-tag: '22.11'
    source-depth: 1
    meson-parameters:
      - --prefix=/usr
    parse-info: [usr/share/metainfo/io.posidon.Paper.appdata.xml]
    build-snaps:
      - blueprint-compiler
    override-pull: |
      craftctl default
      sed -i 's#1.2.0#>=1.2.0#g' $CRAFT_PART_SRC/src/meson.build

slots:
  paper:
    interface: dbus
    bus: session
    name: io.posidon.Paper

apps:
  paper:
    command: usr/bin/io.posidon.Paper
    common-id: io.posidon.Paper
    extensions: [gnome]
    desktop: usr/share/applications/io.posidon.Paper.desktop
    plugs:
      - home
      - removable-media
