name: paper # you probably want to 'snapcraft register <name>'
version: '22.11'
adopt-info: paper
base: core22 # the base snap is the execution environment for this snap
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
compression: lzo
icon: io.posidon.Paper.svg
contact: soumyadeepghosh2004@zohomail.in
architectures:
  # snapcraft builder builds for all archs when building, so, this is necessary to reduce the number of builds
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf
parts:
  paper:
    # See 'snapcraft plugins'
    plugin: meson
    source: https://gitlab.com/posidon_software/paper.git
    source-tag: $SNAPCRAFT_PROJECT_VERSION
    meson-parameters:
      - --prefix=/usr
    parse-info: [usr/share/metainfo/io.posidon.Paper.appdata.xml]
    build-packages:
      - blueprint-compiler
    override-pull: |
      craftctl default
      sed "s/version: '1.2.0'/version: '>=1.2.0'/" -i src/meson.build
      sed "s|labelled-by: notebook_title;|labelled_by: notebook_title;|" -i src/ui/window/window.blp
      sed "s|labelled-by: icon;|labelled_by: icon;|" -i src/ui/window/notebooks_bar/icon.blp
      sed 's|labelled-by: label;|labelled_by: label;|' -i src/ui/window/sidebar/note_card.blp
      sed 's|described-by: descrption_box;|described_by: descrption_box;|' -i src/ui/window/sidebar/note_card.blp
  cleanup:
    after:  # Make this part run last; list all your other parts here
      - paper
    plugin: nil
    build-snaps:  # List all content-snaps and base snaps you're using here
      - gnome-42-2204
      - gtk-common-themes
      - core22
    override-prime: |
      set -eux
      for snap in "gnome-42-2204" "gtk-common-themes" "core22"; do
      cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done

slots:
  # for GtkApplication registration
  paper:
    interface: dbus
    bus: session
    name: io.posidon.Paper
apps:
  paper:
    command: usr/bin/io.posidon.Paper
    common-id: io.posidon.Paper
    extensions: [gnome]
    desktop: usr/share/applications/io.posidon.Paper.desktop
    plugs:
      - home
      - removable-media
      - mount-observe
